### ISSUE TITLE
Method to list all customers

### ISSUE THREAD

**Issue by rudrankriyam** [mauryaratan/lemonsqueezy-swift#1]
Hi! 
Thank you for making this library! I wonder if we can currently [list all the customers](https://docs.lemonsqueezy.com/api/customers#list-all-customers) using the endpoint `v1/customers` because I couldn't find any method for it. 

If you are currently not working on this, I can chime in and create a PR for it!

**Comment by mauryaratan** [comment]
Added in the latest release https://github.com/mauryaratan/lemonsqueezy-swift/commit/ef3918be1a1da083ee771a9429295e84c2e29111
