### ISSUE TITLE
Orders API broken

### ISSUE THREAD

**Issue by biocross** [mauryaratan/lemonsqueezy-swift#5]
First of all thanks for creating this! It's a very comprehensive coverage of the LemonSqueezy API!

Just wanted to inform you that the `getOrders` function now seems to be broken, and on investigation I found out that it's failing during JSON decode. This is likely due to some sort of API format change by LS (although I can't seem to spot it in the [API chaneglog ](https://docs.lemonsqueezy.com/api/changelog). 

The library is not actually surfacing the JSON Decoding error, which is why I'm unable to figure out exactly what key / value is causing the issue. 

I see some other apps are also broken, so this is likely a change by LS that's causing this. Nevertheless, the models might require some changes to work again.

**Comment by biocross** [comment]
Looks like I found the issue! The `order_number` field in the Order model has changed from a `Int` -> `String`

**Comment by mauryaratan** [comment]
Hey @biocross,

Thanks for letting me know. It appears this change was unintentional in Lemon Squeezy API and `order_number` should still be `Int`. We'll get that fixed 👍🏻

**Comment by biocross** [comment]
Ah I didn't notice you actually work for LS! Thank you, it works now!
